mod activation;
pub use activation::{ActivationLayer, Relu, Sigmoid};
mod flatten;
pub use flatten::FlattenLayer;
mod input;
pub use input::InputLayer;
mod linear;
pub use linear::{BiasLayer, LinearLayer};
mod parallel;
pub use parallel::ParallelLayer;
mod sequence;
pub use sequence::Sequence;
mod softmax;
pub use softmax::SoftmaxLayer;
